//
//  ViewController.swift
//  AlamofireTemplate
//
//  Created by Sarvad shetty on 2/9/18.
//  Copyright © 2018 Sarvad shetty. All rights reserved.
//

import UIKit
import Alamofire
import SwiftyJSON



class ViewController: UIViewController,UITextFieldDelegate {
    
    //MARK:IBOutlets
    @IBOutlet weak var first: UILabel!
    @IBOutlet weak var second: UILabel!
    @IBOutlet weak var third: UILabel!
    @IBOutlet weak var fourth: UILabel!
    @IBOutlet weak var firstTextField: UITextField!
    @IBOutlet weak var secondTextField: UITextField!
    @IBOutlet weak var thirdTextField: UITextField!
    @IBOutlet weak var scrollView: UIScrollView!
    
    
    
    //MARK:Constants
     let finalURLString = "https://jsonplaceholder.typicode.com/posts"
    let user = userInput()
    
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
       
        getFunction(url: finalURLString)
        
    }

    
    
    //MARK: Networking Methods
    
    //implementing get request
   func getFunction(url:String){
    Alamofire.request(url, method: .get).responseJSON { (response) in
        if response.result.isFailure{
            print(response.error!)
        }
        else if response.result.isSuccess{
            let jsonData = JSON(response.value!)
            print(jsonData)
            self.updateLabels(data: jsonData)
            
        }
    }
    }
    //implementing post request
    func postFunction(parameters:[String:String],url:String){
        Alamofire.request(url, method: .post, parameters: parameters ).responseJSON { (response) in
            if response.result.isFailure{
                print(response.error!)
            }else if response.result.isSuccess{
                let jsonData2 = JSON(response.value!)
                print(jsonData2)
                self.postData(data: jsonData2)
            }
        }
    }

    //MARK: Update label using JSON Data
    func updateLabels(data:JSON){
        //just accessing the first set of values for test purposes
        first.text = data[0]["title"].stringValue
        second.text = data[0]["userId"].stringValue
        third.text = data[0]["id"].stringValue
        fourth.text = data[0]["body"].stringValue
    }
    
    func postData(data:JSON){
        first.text = data["title"].stringValue
        second.text = data["userId"].stringValue
        third.text = data["id"].stringValue
        fourth.text = data["body"].stringValue
    }
    
    
    
    
    //MARK: IBActions
    @IBAction func buttonAction(_ sender: UIButton) {
  
        let param :[String:String] = ["title":user.firstText,"userId":user.secondText,"body":user.thirdText]
        postFunction(parameters: param, url: finalURLString)
        // we wont be entering an id no. as it will be generated by the free api
        firstTextField.text = ""
        secondTextField.text = ""
        thirdTextField.text = ""
        
    }
    
    //MARK: Functions
    func textFieldDidBeginEditing(_ textField: UITextField) {
        switch textField.tag {
        case 1:
            print("do nothing")
            break
        case 2:
            scrollView.setContentOffset(CGPoint.init(x: 0, y: 100), animated: true)
            break
        case 3:
            scrollView.setContentOffset(CGPoint.init(x: 0, y: 170), animated: true)
            break
        default:
            //
            break
        }
    }
    func textFieldDidEndEditing(_ textField: UITextField) {
        switch textField.tag {
        case 1:
            user.firstText = firstTextField.text!
            break
        case 2:
            user.secondText = secondTextField.text!
            break
        case 3:
            user.thirdText = thirdTextField.text!
            break
        default:
            //
            break
        }
        scrollView.setContentOffset(CGPoint.init(x: 0, y: 0), animated: true)
    }
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        return true
    }

    
    
}

